# Generated by Django 5.0.2 on 2024-02-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopseeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offers',
            field=models.BooleanField(default=False, help_text='0-show,1-Hidden'),
        ),
    ]
