# Generated by Django 5.0.2 on 2024-02-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopseeapp', '0002_product_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aboutproduct1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='aboutproduct2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
