# Generated by Django 5.0.2 on 2024-02-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopseeapp', '0008_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Landmark',
            field=models.CharField(blank=True, default='Add Address', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, default='Add Address', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='Add Address', max_length=250, null=True),
        ),
    ]
