# Generated by Django 5.0.2 on 2024-02-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopseeapp', '0009_profile_landmark_profile_address_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pincode',
            field=models.IntegerField(blank=True, default=1, max_length=8),
            preserve_default=False,
        ),
    ]
