# Generated by Django 5.0.2 on 2024-02-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopseeapp', '0015_review_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created_at',
            new_name='created',
        ),
    ]
